package de.greenrobot.daoexample;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table CUSTOMER.
 */
public class Customer extends CustomerBase  {
    public Customer() {
    }

    public Customer(Long id) {
        super(id);
    }

    public Customer(Long id, String name) {
        super(id, name);
    }

}
