package de.greenrobot.daoexample;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table NOTE.
 */
@Test
@Test2( singleValueeee )
@Test3( key2 = "value2", key1 = 5 )
@Test4( key2 = "value2", key1 = null )
public class Note extends NoteBase  {
    public Note() {
    }

    public Note(Long id) {
        super(id);
    }

    public Note(Long id, String text, String comment, java.util.Date date, Integer __gender, java.util.List<String> userIds) {
        super(id, text, comment, date, __gender, userIds);
    }

}
