package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table NOTE.
 */
public class Note extends NoteBase  {
    public Note() {
    }

    public Note(Long id) {
        super(id);
    }

    public Note(Long id, String text, String comment, java.util.Date date, java.util.List<String> userIds) {
        super(id, text, comment, date, userIds);
    }

}
