package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table ORDERS.
 */
public class Order extends OrderBase  {
    public Order() {
    }

    public Order(Long id) {
        super(id);
    }

    public Order(Long id, java.util.Date date, long customerId, byte[] serializedCustomer) {
        super(id, date, customerId, serializedCustomer);
    }

}
